services:
  - type: web
    name: meal-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn wsgi:app --bind 0.0.0.0:$PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: FLASK_DEBUG
        value: false
      - key: COHERE_API_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false 